investMeapp/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "investmeapp"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    # path('login/', views.login, name='login'),
    path('investment/', views.investment, name='investment'),
    path('profile/', views.profile, name='profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('request_withdrawal/', views.request_withdrawal, name='request_withdrawal'),
    path('manage_members/', views.manage_members, name='manage_members'),
    path('delete_member/<int:member_id>/', views.delete_member, name='delete_member'),
    path('update_investment/<int:investment_id>/', views.update_investment, name='update_investment'),
    path('update_roi/', views.update_roi, name='update_roi'),
    path('manage_withdrawals/', views.manage_withdrawals, name='manage_withdrawals'),
    path('approve_withdrawal/<int:withdrawal_id>/', views.approve_withdrawal, name='approve_withdrawal'),
    path('paystack-webhook/', views.paystack_webhook, name='paystack_webhook'),
    path('members/add/', views.MemberCreateView.as_view(), name='member-add'),
    path('change_password/', views.change_password, name='change_password'),
]

multivestproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from multivestshop.views import indexView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexView.as_view(),name='index' ),
    path('accounts/', include('allauth.urls')),
    path('multivest/',include('multivestshop.urls'),name='multivestshop'),
    path('invest/',include('investMeapp.urls'),name='investMeapp')
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    
    

multivestshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,signup,initialize_payment,payment_callback,paystack_webhook,
    order_detail,
    order_list
)

app_name = 'multivestshop'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('signup/', signup, name='signup'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('initialize_payment/', initialize_payment, name='initialize_payment'),
    path('payment_callback/', payment_callback, name='payment_callback'),
     path('orders/', order_list, name='order_list'),
    path('orders/<str:ref_code>/', order_detail, name='order_detail'),
]

multivestshop/models.py
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.utils import timezone
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver


CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
class Category(models.Model):
    name = models.CharField(max_length=100)
    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ManyToManyField(Category)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("multivestshop:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("multivestshop:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("multivestshop:remove-from-cart", kwargs={
            'slug': self.slug
        })
    def get_category(self):
        return self.category.name
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image.path)
            if img.height > 300 or img.width > 300:
                new_img = (300, 300)
                img.thumbnail(new_img)
                img.save(self.image.path)


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return f"{self.user.username} - {self.ref_code}"

    def get_total(self):
        total = sum(order_item.get_final_price() for order_item in self.items.all())
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/cart.html
{% extends 'base.html' %}

{% block content %}


<main class="mt-5 pt-4">

<!-- Cart Page Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">Products</th>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total</th>
                    <th scope="col">Handle</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">
                            <div class="d-flex align-items-center">
                                <img src="{{ order_item.item.image.url }}" class="img-fluid me-5 rounded-circle" style="width: 80px; height: 80px;" alt="">
                            </div>
                        </th>
                        <td>
                            <p class="mb-0 mt-4">{{ order_item.item.title }}</p>
                        </td>
                        <td>
                            <p class="mb-0 mt-4">$ {{ order_item.item.price }}</p>
                        </td>
                        <td>                            
                            <div class="input-group quantity mt-4" style="width: 100px;">
                                <div class="input-group-btn">
                                    <a class="btn btn-sm btn-plus rounded-circle bg-light border" href="{% url 'multivestshop:remove-single-item-from-cart' order_item.item.slug %}">
                                        <i class="fa fa-minus"></i>
                                    </a>
                                </div>
                                <input type="text" class="form-control form-control-sm text-center" value="{{ order_item.quantity }}" disabled>
                                <div class="input-group-btn">
                                    <a class="btn btn-sm btn-plus rounded-circle bg-light border " href="{% url 'multivestshop:add-to-cart' order_item.item.slug %}">
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </div>
                            </div>
                        </td>
                        <td>
                            <p class="mb-0 mt-4">
                                {% if order_item.item.discount_price %}
                                ${{ order_item.get_total_discount_item_price }}
                                <span class="badge badge-primary">
                                    Saving ${{ order_item.get_amount_saved }}
                                </span>
                                {% else %}
                                ${{ order_item.get_total_item_price }}
                                {% endif %}
                            </p>
                        </td>
                        <td>
                            <a class="btn btn-md rounded-circle bg-light border mt-4" href="{% url 'multivestshop:remove-from-cart' order_item.item.slug %}">
                                <i class="fa fa-times text-danger"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='5'>Your cart is empty</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                        <a class='btn btn-primary float-right' href="{% url 'multivestshop:home' %}">Continue shopping</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% if object.coupon %}
        <div class="mt-5">
            <p><b>Coupon</b>
            <b>-${{ object.coupon.amount }}</b></a>
            <!-- <input type="text" class="border-0 border-bottom rounded me-5 py-3 mb-4" placeholder="Coupon Code">
            <button class="btn border-secondary rounded-pill px-4 py-3 text-primary" type="button">Apply Coupon</button> -->
        </div>
        {% endif %}
        {% if object.get_total %}
        <div class="row g-4 justify-content-end">
            <div class="col-8"></div>
            <div class="col-sm-8 col-md-7 col-lg-6 col-xl-4">
                <div class="bg-light rounded">
                    <div class="p-4">
                        <h1 class="display-6 mb-4">Cart <span class="fw-normal">Total</span></h1>
                        <div class="d-flex justify-content-between mb-4">
                        </div>
                        <div class="d-flex justify-content-between">
                        </div>
                    </div>
                    <div class="py-4 mb-4 border-top border-bottom d-flex justify-content-between">
                        <h5 class="mb-0 ps-4 me-4">Total</h5>
                        <p class="mb-0 pe-4">${{ object.get_total }}</p>
                    </div>
                    <a class="btn btn-warning border-secondary rounded-pill px-4 py-3 text-white text-uppercase mb-4 ms-4"
                    href="{% url 'multivestshop:checkout' %}" type="button">Proceed Checkout</a>
                    <a class="btn btn-primary border-secondary  rounded-pill px-4 py-3 text-white text-uppercase mb-4 ms-4"
                    href="{% url 'multivestshop:home' %}" type="button">Continue shopping</a>
                </div>
            </div>
        </div>
        {%endif %}
    </div>
</div>
<!-- Cart Page End -->
</main>
{% endblock content %}

templates/initialize_payment.html
<!DOCTYPE html>
<html>
<head>
    <title>Initialize Payment</title>
</head>
<body>
    <h2>Make a Payment</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Pay Now</button>
    </form>
</body>
</html>

templates/navbar.html
{% load static %}

{% load cart_template_tags %}

<!-- Navbar start -->
<div class="container-fluid fixed-top">
    
    <div class="container topbar bg-primary d-none d-lg-block">
        <div class="d-flex justify-content-between">
            <div class="top-info ps-2">
                <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#" class="text-white">123 Street, New York</a></small>
                <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#" class="text-white">Email@Example.com</a></small>
            </div>
            <div class="top-link pe-2">
                <a href="#" class="text-white"><small class="text-white mx-2">Privacy Policy</small>/</a>
                <a href="#" class="text-white"><small class="text-white mx-2">Terms of Use</small>/</a>
                <a href="#" class="text-white"><small class="text-white ms-2">Sales and Refunds</small></a>
            </div>
        </div>
    </div>
    <div class="container px-0">
        <nav class="navbar navbar-light bg-white navbar-expand-xl">
            <div class="py-2 px-3">
                <a href="/" class="navbar-brand">
                        <!-- <img src="{% static 'img/delainah.png' %}" alt="" class="img-fluid position-relative" height="50"> -->
                        <h1 class="text-primary display-24">DELAINAH OPTIMAH</h1>
                </a>
            </div>
            <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="fa fa-bars text-primary"></span>
            </button>
            <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                <div class="navbar-nav mx-auto">
                    <a href="/" class="nav-item nav-link">Home</a>                            
                    <!-- <a href="contact.html" class="nav-item nav-link">Contact</a> -->
                </div>
                {% if request.user.is_authenticated %}
                <div class="d-flex m-3 me-0">
                    <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fas fa-search text-primary"></i></button>
                    <a href="{% url 'multivestshop:order-summary' %}" class="position-relative me-4 my-auto"">
                        <i class="fa fa-shopping-bag fa-2x"></i>
                        <span class="position-absolute bg-secondary rounded-circle d-flex align-items-center justify-content-center text-dark px-1" style="top: -5px; left: 15px; height: 20px; min-width: 20px;">{{ request.user|cart_item_count }}</span>
                    </a>
                    <a href="{% url 'account_logout' %}" class="my-auto">
                        <i class="fas fa-user fa-2x"></i>
                    </a>
                    {% else %}
                    <a href="{% url 'account_login' %}" class="nav-item nav-link">
                        Login
                    </a>
                    <a href="{% url 'multivestshop:signup' %}" class="nav-item nav-link">
                            Signup
                    </a>
                    <a href="{% url 'investmeapp:login' %}" class="nav-item nav-link">
                        Member Login
                    </a>
                    <a href="{% url 'investmeapp:signup' %}" class="nav-item nav-link">
                            Member Signup
                    </a>
                </div>
                {% endif %}
            </div>
        </nav>
    </div>
</div>
<!-- Navbar End -->

templates/order_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
    <!-- Fruits Shop Start-->
    <div class="container-fluid page-header py-5"></div>
    <div class="container py-5">
        <h1>Order Detail: {{ order.ref_code }}</h1>
        <p>Total: {{ order.get_total }} USD</p>
        <p>Ordered Date: {{ order.ordered_date }}</p>
        <h2>Items</h2>
        <div class="card">
            <div class="card-body">
                <!-- Table with hoverable rows -->
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Item</th>
                            <th>Name</th>
                            <th>Quantity</th>
                            <th>Price</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in order.items.all %}
                            <tr>
                                <td scope="row">
                                    <div class="d-flex align-items-center">
                                        <img src="{{ item.item.image.url }}" class="img-fluid me-5 rounded-circle" style="width: 80px; height: 80px;" alt="">
                                    </div>
                                </td>
                                <td><p class="mb-0 mt-4">{{ item.item.title }}</p></td>
                                <td><p class="mb-0 mt-4">{{ item.quantity }}</p></td>
                                <td><p class="mb-0 mt-4">{{ item.item.price }}</p></td>
                                <td><p class="mb-0 mt-4">{{ item.get_final_price }}</p></td>
                                
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <a href="{% url 'multivestshop:order_list' %}">Back to Orders</a>
    </div>
</main>
{% endblock content %}

templates/order_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

 <main>
    <!-- Fruits Shop Start-->
    <div class="container-fluid page-header py-5"></div>
    <div class="container py-5">
        <h1>Your Orders</h1>
        <div class="card">
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Reference Code</th>
                            <th>Total</th>
                            <th>Ordered Date</th>
                            <th>Ordered Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                            <tr>
                                <td scope="row"><p class="mb-0 mt-4"><a href="{% url 'multivestshop:order_detail' order.ref_code %}">{{ order.ref_code }}</a></p></td>
                                <td><p class="mb-0 mt-4">{{ order.get_total }} USD</p></td>
                                <td><p class="mb-0 mt-4">{{ order.ordered_date }}</p></td>
                                {% if order.ordered %}
                                <td><p class="mb-0 mt-4">Order Made</p></td>
                                {% elif order.being_delivered %}
                                <td><p class="mb-0 mt-4">On the way</p></td>
                                {% elif order.received %}
                                <td><p class="mb-0 mt-4">Fulfilled</p></td>
                                {% endif %}

                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="3">You have no orders.</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'multivestshop:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/product.html
{% extends 'base.html' %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container-fluid py-5 mt-5">
      <!--Grid row-->
      <div class="row wow fadeIn">
        <!--Grid column-->
        <div class="col-md-6 mb-4">
          <img src="{{ object.image.url }}" class="img-fluid" alt="">
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}

templates/request_refund.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <main>    
    <div class="container-fluid page-header py-5"></div>
    <div class="container">
      <div class="row justify-content-center">
          {% for message in messages %}
              <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
      </div>
    </div>
    <div class="container py-5">

      <h2>Request Refund</h2>
      <form method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          <button type='submit' class='btn btn-primary'>Submit</button>
      </form>

    </div>
  </main>

{% endblock content %}